node {
   def mvnHome
   stage('Checkout') { 
      git url: 'file://E:/pixogram/newsfeedservice'
              
      mvnHome = tool 'Local MAVEN'
   }
   stage('Build') {
      // Run the maven build
      if (isUnix()) {
         sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
      } else {
         bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
      }
   }
   
   stage ('Final') {
         build job: 'Docker-Compose-Pipeline', wait: false
        }     
}